import { NodeData } from "@/models";

export const nodeDatas: NodeData[] = [
  {
    id: 1,
    isSecret: false,
    isFolder: true,
    parentId: null,
    children: [
      {
        id: 2,
        isSecret: false,
        isFolder: true,
        parentId: null,
        children: [],
        content: {
          id: 2,
          name: "フォルダ2",
          createdAt: new Date(),
          updatedAt: new Date(),
          deletedAt: null,
        },
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        authorId: 1,
      },
    ],
    content: {
      id: 1,
      name: "フォルダ1",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    authorId: 1,
  },
  {
    id: 3,
    isSecret: false,
    isFolder: true,
    parentId: null,
    children: [
      {
        id: 4,
        isSecret: false,
        isFolder: true,
        parentId: null,
        children: [
          {
            id: 5,
            isSecret: false,
            isFolder: false,
            parentId: null,
            children: [],
            content: {
              id: 5,
              name: "メモ3",
              body: "メモ3の本文です。",
              createdAt: new Date(),
              updatedAt: new Date(),
              deletedAt: null,
            },
            createdAt: new Date(),
            updatedAt: new Date(),
            deletedAt: null,
            authorId: 1,
          },
        ],
        content: {
          id: 4,
          name: "フォルダ3",
          createdAt: new Date(),
          updatedAt: new Date(),
          deletedAt: null,
        },
        createdAt: new Date(),
        updatedAt: new Date(),
        deletedAt: null,
        authorId: 1,
      },
    ],
    content: {
      id: 3,
      name: "フォルダ4",
      createdAt: new Date(),
      updatedAt: new Date(),
      deletedAt: null,
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    authorId: 1,
  },
];
